apiVersion: apps/v1
kind: Deployment
metadata:
  name: mcp
  namespace: activity2
spec:
  replicas: 4
  selector:
    matchLabels:
      app: mcp
  template:
    metadata:
      labels:
        app: mcp
    spec:
      volumes:
        - name: html
          emptyDir: {}
      containers:
        - name: backend
          image: debian:11.8-slim
          imagePullPolicy: Always
          volumeMounts:
            - name: html
              mountPath: /html
          command: ["/bin/sh", "-c"]
          args:
            - |
              while true; do
                date > /html/index.html;
                sleep 60;
              done
        - name: frontend
          image: nginx:1.24.0-alpine-slim
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: /usr/share/nginx/html
              name: html
          ports:
            - containerPort: 80
